### ISSUE TITLE
Error when creating a BPM project

### ISSUE THREAD

**Issue by tin2tin** [samytichadou/blender_project_manager#1]
![image](https://user-images.githubusercontent.com/1322593/77168482-342b4880-6ab8-11ea-9159-259984b12e6e.png)

The folder is empty.

**Comment by samytichadou** [comment]
hi, can you confir me a shot file has been created at the specified path ?
C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend

thkx

**Comment by tin2tin** [comment]
Yes, this is the file:
[Project Prefix_S001_v001.zip](https://github.com/samytichadou/blender_project_manager/files/4365218/Project.Prefix_S001_v001.zip)

**Comment by samytichadou** [comment]
ok i just pushed a commit with a error handling with print,it will raise another error for sure, but you will see some infos in the console before. Can you try it again with last version, launching blender from a command line ? and btw which version of blender are you using ?

**Comment by tin2tin** [comment]
I'm using a build from the latest master. This is the output in cmd:
```Blender Project Manager --- File successfully deleted : C:\Users\user\Documents\BPM\Project Prefix_S001\python_temp.py
Blender Project Manager --- Scenes linked from : C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Blender Project Manager --- Opening C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Read blend: C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas found, loading from C:\Users\user\Documents\BPM\project_data.json
Blender Project Manager --- Setting property : name
Blender Project Manager --- Setting property : project_prefix
Blender Project Manager --- Setting property : framerate
Blender Project Manager --- Setting property : resolution_x
Blender Project Manager --- Setting property : resolution_y
Blender Project Manager --- Setting property : project_folder
Blender Project Manager --- Setting property : edit_file_pattern
Blender Project Manager --- Setting property : edit_scene_keyword
Blender Project Manager --- Setting property : shot_prefix
Blender Project Manager --- Setting property : shot_digits
Blender Project Manager --- Setting property : shot_version_suffix
Blender Project Manager --- Setting property : shot_version_digits
Blender Project Manager --- Setting property : shot_start_frame
Blender Project Manager --- Setting property : default_shot_length
Blender Project Manager --- Project Datas loaded
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 27, in getLastVersion
    filepath = os.path.join(folder, corresponding_files_sorted[0][0])
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 27, in getLastVersion
    filepath = os.path.join(folder, corresponding_files_sorted[0][0])
IndexError: list index out of range

location: <unknown location>:-1```

**Comment by samytichadou** [comment]
ok new error this time, i just pushed a new debug version to try to get more infos, can you run it ? (sorry for the back and forths, but i can't reproduce the error from here...)

**Comment by tin2tin** [comment]
```Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas not found
Info: Total files 0 | Changed 0 | Failed 0
Blender Project Manager --- Saving to json
Blender Project Manager --- Successfully saved to json
Blender Project Manager --- Starting new shot creation
Blender Project Manager --- Checking on timeline for available space
Blender Project Manager --- Creating New Shot Folder : C:\Users\user\Documents\BPM\Project Prefix_S001
Blender Project Manager --- Launching Command : C:\Users\user\Documents\BPM\Project Prefix_S001\python_temp.py
Blender Project Manager --- Python script successfully created
Blender Project Manager --- Launching Command : C:\Users\user\Documents\build_windows_x64_vc16_Release\bin\Release\blender.exe  --background --python "C:\Users\user\Documents\BPM\Project Prefix_S001\python_temp.py" --
Blender 2.83 (sub 10) (hash a696053545e9 built 2020-03-21 11:43:52)
Read prefs: C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Users\user\Documents\build_windows_x64_vc16_Release\bin\Release\2.83\python
Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas not found
Blender Project Manager --- Setting Shot scene variables
Blender Project Manager --- Saving file
Info: Total files 0 | Changed 0 | Failed 0

Blender quit
Blender Project Manager --- File successfully deleted : C:\Users\user\Documents\BPM\Project Prefix_S001\python_temp.py
Blender Project Manager --- Scenes linked from : C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Blender Project Manager --- Opening C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Read blend: C:\Users\user\Documents\BPM\Project Prefix_S001\Project Prefix_S001_v001.blend
Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas found, loading from C:\Users\user\Documents\BPM\project_data.json
Blender Project Manager --- Setting property : name
Blender Project Manager --- Setting property : project_prefix
Blender Project Manager --- Setting property : framerate
Blender Project Manager --- Setting property : resolution_x
Blender Project Manager --- Setting property : resolution_y
Blender Project Manager --- Setting property : project_folder
Blender Project Manager --- Setting property : edit_file_pattern
Blender Project Manager --- Setting property : edit_scene_keyword
Blender Project Manager --- Setting property : shot_prefix
Blender Project Manager --- Setting property : shot_digits
Blender Project Manager --- Setting property : shot_version_suffix
Blender Project Manager --- Setting property : shot_version_digits
Blender Project Manager --- Setting property : shot_start_frame
Blender Project Manager --- Setting property : default_shot_length
Blender Project Manager --- Project Datas loaded
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 27, in getLastVersion
    corresponding_files.append([filename, version_number])
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 27, in getLastVersion
    corresponding_files.append([filename, version_number])
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by samytichadou** [comment]
ok that's really weird, you should have some "DEBUG ---" ... lines in here. 
The error is triggered from a "Back to Edit" from a shot project isn't it ? not when creating a BPM project ?
(and did you correctly uninstall/reinstall it ?)

**Comment by tin2tin** [comment]
I tried several times starting over, but now I see the debug lines:
```Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas not found
Info: Total files 0 | Changed 0 | Failed 0
Blender Project Manager --- Saving to json
Blender Project Manager --- Successfully saved to json
Blender Project Manager --- Starting new shot creation
Blender Project Manager --- Checking on timeline for available space
Blender Project Manager --- Creating New Shot Folder : C:\Users\user\Documents\BPM\Project_prefix_S001
Blender Project Manager --- Launching Command : C:\Users\user\Documents\BPM\Project_prefix_S001\python_temp.py
Blender Project Manager --- Python script successfully created
Blender Project Manager --- Launching Command : C:\Users\user\Documents\build_windows_x64_vc16_Release\bin\Release\blender.exe  --background --python "C:\Users\user\Documents\BPM\Project_prefix_S001\python_temp.py" --
Blender 2.83 (sub 10) (hash a696053545e9 built 2020-03-21 11:43:52)
Read prefs: C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Users\user\Documents\build_windows_x64_vc16_Release\bin\Release\2.83\python
Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas not found
Blender Project Manager --- Setting Shot scene variables
Blender Project Manager --- Saving file
Info: Total files 0 | Changed 0 | Failed 0

Blender quit
Blender Project Manager --- File successfully deleted : C:\Users\user\Documents\BPM\Project_prefix_S001\python_temp.py
Blender Project Manager --- Scenes linked from : C:\Users\user\Documents\BPM\Project_prefix_S001\Project_prefix_S001_v001.blend
Blender Project Manager --- Opening C:\Users\user\Documents\BPM\Project_prefix_S001\Project_prefix_S001_v001.blend
Read blend: C:\Users\user\Documents\BPM\Project_prefix_S001\Project_prefix_S001_v001.blend
Blender Project Manager --- Looking for Project Datas
Blender Project Manager --- Project Datas found, loading from C:\Users\user\Documents\BPM\project_data.json
Blender Project Manager --- Setting property : name
Blender Project Manager --- Setting property : project_prefix
Blender Project Manager --- Setting property : framerate
Blender Project Manager --- Setting property : resolution_x
Blender Project Manager --- Setting property : resolution_y
Blender Project Manager --- Setting property : project_folder
Blender Project Manager --- Setting property : edit_file_pattern
Blender Project Manager --- Setting property : edit_scene_keyword
Blender Project Manager --- Setting property : shot_prefix
Blender Project Manager --- Setting property : shot_digits
Blender Project Manager --- Setting property : shot_version_suffix
Blender Project Manager --- Setting property : shot_version_digits
Blender Project Manager --- Setting property : shot_start_frame
Blender Project Manager --- Setting property : default_shot_length
Blender Project Manager --- Project Datas loaded
DEBUG --- folder : C:\Users\user\Documents\BPM
DEBUG --- pattern : untitled21
DEBUG --- iterate filename : C:\Users\user\Documents\BPM
DEBUG --- iterate filename : C:\Users\user\Documents\BPM
DEBUG --- corresponding files : []
DEBUG --- corresponding files sorted : []
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 32, in getLastVersion
    filepath = os.path.join(folder, corresponding_files_sorted[0][0])
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\operators\back_to_edit.py", line 21, in execute
    filepath = getLastVersion(project_datas.project_folder, project_datas.edit_file_pattern, ".blend")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_project_manager-master\functions\file_functions.py", line 32, in getLastVersion
    filepath = os.path.join(folder, corresponding_files_sorted[0][0])
IndexError: list index out of range

location: <unknown location>:-1


```

**Comment by samytichadou** [comment]
ok, is there a "untitled21.blend" as a edit file in the project folder ("C:\Users\user\Documents\BPM")
that's the thing the addon is looking for. 
The edit file has to be for now in the project folder. Is it the case for you ?

**Comment by tin2tin** [comment]
Not file in that name in that folder:
![image](https://user-images.githubusercontent.com/1322593/77258914-098aec80-6c7e-11ea-8a11-62734ec3edf7.png)

Inside the shot folder is this:
![image](https://user-images.githubusercontent.com/1322593/77258922-1dcee980-6c7e-11ea-9835-d86281d9937f.png)

The JSON file:
```{
    "name": "Project_name",
    "project_prefix": "Project_prefix",
    "framerate": 25,
    "resolution_x": 1920,
    "resolution_y": 1080,
    "project_folder": "C:\\Users\\user\\Documents\\BPM",
    "edit_file_pattern": "untitled21",
    "edit_scene_keyword": "",
    "shot_prefix": "S",
    "shot_digits": 3,
    "shot_version_suffix": "v",
    "shot_version_digits": 3,
    "shot_start_frame": 100,
    "default_shot_length": 100
}```

**Comment by samytichadou** [comment]
aaaaaah ok that where the problem is, yep it isn't clear at all, here's the way to make it work (and how it is designed for now :) )

1) create a blend file where you want your whole project to be, save it. This will be your edit/master file
2) create a bpm project through the operator in the app menu
3) through the sequencer menu, create new shot

You can then open this shot through here and go back to the edit
Last commits also give ability to update the duration of the shot through the edit (one way only)

Does any of this makes sense ? If yes can you try it this way ? cheers !

**Comment by tin2tin** [comment]
Yes, saving my file inside the project manager folder makes it work.

**Comment by tin2tin** [comment]
Cool, now it works without having to copy the file to the folder. Have you tried to use my scene_strip_tools inside the "shots", so your "shots" will contain a scene with camera cutting in the sequencer or is it only the camera in the scene strips is supported in BPM?

EDIT: Seems to only support the Camera setting in the generated scene strips, and not the Sequencer setting. Could have been cool to return an edited strip, but maybe it is wise to keep it simple.  :-)

**Comment by samytichadou** [comment]
@tin2tin for now i keep it as simple as i posibly can to feel some simple workflow need. 
My guess is big company would develop their own tool, so this try is only for short films or little serie. 
But i am planning to add a "convert to shot" operator, which would take the existing scene/video/still image and put it in shot file as a reference, so it could be a perfect addition with your addon ! what do you think ?
